package com.example.jakubkalinowski.contractfoxandroid.Model;

import com.google.firebase.database.Exclude;
import com.google.firebase.database.IgnoreExtraProperties;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Map;

/**
 * Created by Ladimer on 9/26/2016.
 */

@IgnoreExtraProperties

public class Review {


    //this data is autogenerated by firebase
    private String mReviewerId;
    private String mRevieweeId;
    private Map<String, Object> createdAtFirebaseTimestamp;
    //this data is taken from string
    private String mTitle;
    private String mDescription;
    private Double mStars;


    private String firebasePushId;


    public Review() {
    }


    public Review(String reviewerId, String revieweeId,
                  Map<String, Object> firebaseTimestamp, String title,
                  String description, Double stars, String firebasePushId) {
        mReviewerId = reviewerId;
        mRevieweeId = revieweeId;
        createdAtFirebaseTimestamp = firebaseTimestamp;
        mTitle = title;
        mDescription = description;
        mStars = stars;
        this.firebasePushId = firebasePushId;
    }


    public String getReviewerId() {
        return mReviewerId;
    }

    public void setReviewerId(String reviewerId) {
        mReviewerId = reviewerId;
    }

    public String getRevieweeId() {
        return mRevieweeId;
    }

    public void setRevieweeId(String revieweeId) {
        mRevieweeId = revieweeId;
    }

    public Map<String, Object> getCreatedAtFirebaseTimestamp() {
        return createdAtFirebaseTimestamp;
    }

    public void setCreatedAtFirebaseTimestamp(Map<String, Object> createdAtFirebaseTimestamp) {
        this.createdAtFirebaseTimestamp = createdAtFirebaseTimestamp;
    }

    public String getDescription() {
        return mDescription;
    }

    public void setDescription(String description) {
        mDescription = description;
    }

    public Double getStars() {
        return mStars;
    }

    public void setStars(Double stars) {
        mStars = stars;
    }


    public String getTitle() {
        return mTitle;
    }

    public void setTitle(String title) {
        mTitle = title;
    }


    @Exclude
    public long createdAtFirebaseTimestampLong;

    @Exclude
    public long getCreatedAtFirebaseTimestampLong() {
        return (long) createdAtFirebaseTimestamp.get("date");
    }


    public String getFirebasePushId() {
        return firebasePushId;
    }


    @Exclude
    public String getCreatedAtFirebaseTimeStampFormattedString() {
        Calendar c = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("dd MMM yyyy");
        c.setTimeInMillis((long) createdAtFirebaseTimestamp.get("date"));
        return sdf.format(c.getTime());
    }


    @Exclude
    public String reviewerName;

    @Exclude
    public void setReviewerName(String reviewerName) {
        this.reviewerName = reviewerName;
    }

    @Exclude
    public String getReviewerName() {
        return this.reviewerName;
    }


}
